---
#Main installation actions
#https://clickhouse.com/docs/en/getting-started/#installation

- name: Uninstall by YUM | Ensure clickhouse-role package uninstalled
  dnf:
    name: "{{ clickhouse_package }}"
    state: absent
    autoremove: yes
  become: true

- name: Uninstall by YUM | Ensure clickhouse-role repo uninstalled
  yum_repository:
    name: clickhouse-role
    file: clickhouse-role
    state: absent
  become: true

- name: Uninstall by YUM | Ensure clickhouse-role key uninstalled
  rpm_key:
    key: "{{ clickhouse_repo_key }}"
    state: absent
  become: true
