---
# tasks file for vector-role
- name: Get vector-role distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector-role/{{ vector_version }}/vector-role-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-role-{{ vector_version }}-1.x86_64.rpm"
- name: Install vector-role packages
  become: true
  ansible.builtin.yum:
    name:
      - vector-role-{{ vector_version }}-1.x86_64.rpm
  notify: Start vector-role service