---
# tasks file for vector-role
- name: print facts
  debug:
    var: ansible_distribution
- include_tasks: install_CentOS.yml
  when: ansible_distribution == "CentOS"
- include_tasks: install_Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
