---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install Clickhouse
  hosts: vector
  roles:
    - vector-role

- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - lighthouse-role