---
- name: Config | Generate dictionary config
  template:
    src: dicts.j2
    dest: "{{ clickhouse_path_configdir }}/auto_dictionary.xml"
    owner: "{{ clickhouse_user | default('clickhouse-role') }}"
    group: "{{ clickhouse_group | default('clickhouse-role') }}"
    mode: "ug=rw,o-rwx"
  become: true
  when: clickhouse_dicts|length>0 
