---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.73.194
      become_user: root
      remote_user: centos
      ansible-user: centos

vector:
  hosts:
    vector-01:
      ansible_host: 51.250.83.154
      become_user: root
      remote_user: centos
      ansible-user: centos

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.93.71
      become_user: root
      remote_user: centos
      ansible-user: centos